Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using bakery.Models;


namespace bakery.Controllers
{
	[Authorize]
	public class FeedbackController : Controller
	{
		private readonly IFeedbackRepository _feedbackRepository;
		public FeedbackController(IFeedbackRepository feedbackRepository)
		{
			_feedbackRepository = feedbackRepository;
		}

		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Index(Feedback feedback)
		{
			if (ModelState.IsValid)
			{
				_feedbackRepository.AddFeedback(feedback);
				return RedirectToAction("FeedbackComplete");
			}
			return View(feedback);
		}

		public IActionResult FeedbackComplete()
		{
			return View();
		}
	}
}

Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="/node_modules/bootstrap/dist/css/bootstrap.min.css" />
		<link rel="stylesheet" type="text/css" href="/css/styles.css" />
		@if(ViewBag.pageTitle != null) {
			<title>Shapira's Bakery | @ViewBag.pageTitle</title>
		}
		else {
			<title>Shapira's Bakery</title>
		}

	</head>
	<body>
		<nav class="navbar navbar-light bg-light">
			<ul class="nav flex-row flex-fill justify-content-between">
				<li class="nav-item">
					<a asp-controller="Home" asp-action="Index" class="nav-link active">
						Home
					</a>
				</li>
				@if(SignInManager.IsSignedIn(User)) {
					<li class="nav-item">
						<a asp-controller="Feedback" asp-action="Index" class="nav-link">
							Contact Us
						</a>
					</li>
					<li class="nav-item">
						<form asp-area="" asp-controller="Account" asp-action="Logout"
							id="logout-form" method="POST" class="navbar-right">
							<button onclick="document.getElementById('logout-form').submit()"
								class="btn btn-danger">
								Logout
							</button>
						</form>
					</li>
				}
				else {
					<li class="nav-item">
						<a asp-controller="Account" asp-action="Register" class="nav-link">
							Register
						</a>
					</li>
					<li class="nav-item">
						<a asp-controller="Account" asp-action="Login" class="nav-link">
							Login
						</a>
					</li>
				}
			</ul>
		</nav>
		@RenderBody()
		<script src="/node_modules/jquery/dist/jquery.min.js"></script>
		<script src="/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
		<script src="/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
	</body>
</html>